// Code generated by "stringer -type=ErrorClass"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown - -1]
	_ = x[Success-0]
	_ = x[NoSuchRedirect-40001]
	_ = x[InvalidRequest-40999]
}

const (
	_ErrorClass_name_0 = "UnknownSuccess"
	_ErrorClass_name_1 = "NoSuchRedirect"
	_ErrorClass_name_2 = "InvalidRequest"
)

var (
	_ErrorClass_index_0 = [...]uint8{0, 7, 14}
)

func (i ErrorClass) String() string {
	switch {
	case -1 <= i && i <= 0:
		i -= -1
		return _ErrorClass_name_0[_ErrorClass_index_0[i]:_ErrorClass_index_0[i+1]]
	case i == 40001:
		return _ErrorClass_name_1
	case i == 40999:
		return _ErrorClass_name_2
	default:
		return "ErrorClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
